Revert "dumpon: fix building with OpenSSL 3.0"
/tmp/cirrus-ci-build/sbin/dumpon/dumpon.c:568:3: error: call to undeclared function 'ERR_load_crypto_strings'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
                ERR_load_crypto_strings();
                ^

This reverts commit f056356cf61f9d28611f8a1730ed43c5609a7031.