Squashed commit of the following:
commit 24958b70830a043d504194e0f0cf3ce10ee67d1e
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Oct 8 19:12:04 2024 +0200

    Bump llvm-project version numbers to llvmorg-19.1.1-0-gd401987fe349.

    PR:		280562
    MFC after:	1 month

commit d67262c8a43e6ef965ad05c03d026a8bace145ba
Merge: d9b242801571 0370629593a6
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Oct 8 19:05:26 2024 +0200

    Merge llvm-project release/19.x llvmorg-19.1.1-0-gd401987fe349

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project release/19.x llvmorg-19.1.1-0-gd401987fe349,
    a.k.a. 19.1.1 release.

    PR:		280562
    MFC after:	1 month

commit d9b242801571a156b1a60a04e741e573c532343b
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Sep 22 11:52:47 2024 +0200

    Bump llvm-project version numbers to llvmorg-19.1.0-0-ga4bf6cd7cfb1.

    PR:		280562
    MFC after:	1 month

commit 664209ed98adfc82694ea87aad11ff827b2352de
Merge: d4e7386e762a 1de139fdd502
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Sep 22 11:48:03 2024 +0200

    Merge llvm-project release/19.x llvmorg-19.1.0-0-ga4bf6cd7cfb1

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project release/19.x llvmorg-19.1.0-0-ga4bf6cd7cfb1,
    a.k.a. 19.1.0 release.

    PR:		280562
    MFC after:	1 month

commit d4e7386e762ab03970988da123a269b9dfc5d8ee
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Sep 11 12:17:00 2024 +0200

    Merge commit 6dbdb8430b49 from llvm git (by Nikolas Klauser):

      [Clang] Fix crash due to invalid source location in __is_trivially_equality_comparable (#107815)

      Fixes #107777

    This fixes an assertion failure building www/qt5-webengine:

      Assertion failed: (Loc.isValid() && "point of instantiation must be valid!"), function setPointOfInstantiation, file contrib/llvm-project/clang/include/clang/AST/DeclTemplate.h, line 1938.

commit c5e59749ee0e22a23454d7627a62d21a1ecbc9f5
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Sep 4 20:59:32 2024 +0200

    Bump llvm-project version numbers to llvmorg-19.1.0-rc4-0-g0c641568515a.

    PR:		280562
    MFC after:	1 month

commit 9ec5b09942db01fc52a951d5ada178cd791e8250
Merge: 8e6648276bef 7432c96084d7
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Sep 4 16:31:28 2024 +0200

    Merge llvm-project release/19.x llvmorg-19.1.0-rc4-0-g0c641568515a

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project release/19.x llvmorg-19.1.0-rc4-0-g0c641568515a.

    PR:		280562
    MFC after:	1 month

commit 8e6648276befe7f65201eff63ac8c7c8fcc12b3b
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Aug 25 13:15:45 2024 +0200

    Bump llvm-project version numbers to llvmorg-19.1.0-rc3-0-g437434df21d8.

    PR:		280562
    MFC after:	1 month

commit 85635e42fad6236f18954624f905e07e1c2d5068
Merge: 5b56f0424496 adf62863f35c
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Aug 25 13:12:58 2024 +0200

    Merge llvm-project release/19.x llvmorg-19.1.0-rc3-0-g437434df21d8

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project release/19.x llvmorg-19.1.0-rc3-0-g437434df21d8.

    PR:		280562
    MFC after:	1 month

commit 5b56f0424496b7204f630852447c9dc467091d4c
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Aug 6 19:40:15 2024 +0200

    Bump llvm-project version numbers to llvmorg-19.1.0-rc2-0-gd033ae172d1c.

    PR:		280562
    MFC after:	1 month

commit 6ad58c00076007366f8f86f97beaf0904fc4e72b
Merge: ceae0ad670c2 9b9503334fa8
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Aug 6 15:37:26 2024 +0200

    Merge llvm-project release/19.x llvmorg-19.1.0-rc2-0-gd033ae172d1c

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project release/19.x llvmorg-19.1.0-rc2-0-gd033ae172d1c.

    PR:		280562
    MFC after:	1 month

commit ceae0ad670c2ab76e73e67fba851a5dfa82abb4d
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Aug 6 10:47:32 2024 +0200

    Update libcxx.imp for headers that were reintroduced by libcxx-compat reverts.

commit 2c3ce177f5d92e6e759a55504d94b7c7635bd0cf
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:49:15 2024 +0200

    Apparently module.modulemap is now just copied.

commit 4ee8e73cee7fa02699b146a13acf45806938b646
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:41:08 2024 +0200

    Install headers that were reintroduced by libcxx-compat reverts.

commit 780a034774fee46a67cd26f31195b36467a536bb
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:36:02 2024 +0200

    Don't remove headers that were reintroduced by libcxx-compat reverts.

commit ac2b00321a761d9726c4811589833abb88ace5c9
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:27:51 2024 +0200

    libcxx-compat: revert llvmorg-19-init-4003-g55357160d0e1:

      [libc++] Use GCC type traits builtins for remove_cv and remove_cvref (#81386)

      They have been added recently to GCC without support for mangling. This
      patch uses them in structs and adds aliases to these structs instead of
      the builtins directly.

commit e253155be3c237f11e61fd016e05a0d47c5244fa
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:27:22 2024 +0200

    libcxx-compat: revert llvmorg-19-init-4504-g937a5396cf3e:

      [libc++] Remove unused includes from __type_traits/is_convertible.h (#83747)

commit 8cecf80680fb016a65e4d1b7ae1ab9b4410667a1
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:26:58 2024 +0200

    libcxx-compat: revert llvmorg-19-init-5639-ga10aa4485e83:

      [libc++] Simplify the implementation of remove_reference (#85207)

      GCC 13 introduced the type trait `__remove_reference`. We can simplify
      the implementation of `remove_reference` a bit by using it.

commit 7ede2357d1898544156ced7f617f83856e5b9d9b
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:26:27 2024 +0200

    libcxx-compat: revert llvmorg-19-init-8667-g472b612ccbed:

      [libc++][NFC] Remove unused includes from <__type_traits/remove_cv.h> (#88752)

commit 3f33aa957ac1725c4707dd7ce5ec218d1bbfc5a7
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:26:02 2024 +0200

    libcxx-compat: revert llvmorg-19-init-17473-g69fecaa1a455:

      [libc++] Clean up some now dead code with the upgrade to GCC 14 (#97746)

commit 2578c62837c4cc7415e334473322fdd0e595a271
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:25:18 2024 +0200

    libcxx-compat: revert llvmorg-19-init-17727-g0eebb48fcfbc:

      [libc++] Merge is_member{,_object,_function}_pointer.h (#98727)

      The implementations for these traits have been simplified quite a bit,
      since we have builtins available for them now.

commit d24a2473f74b7db0a444d7d411f6e9c7761e9b1e
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:17:59 2024 +0200

    libcxx-compat: revert llvmorg-19-init-17728-g30cc12cd818d:

      [libc++] Simplify the implementation of is_null_pointer a bit (#98728)

commit d88cbad41275429384bed85d9a5cf8a67390e9f0
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:17:17 2024 +0200

    libcxx-compat: revert llvmorg-19-init-17853-g578c6191eff7:

      [libc++] Simplify std::is_void (#99033)

commit 1be2ebbdd1fb067751dea10386cbb0ae1025cfec
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:16:04 2024 +0200

    libcxx-compat: revert llvmorg-19-init-18062-g4dfa75c663e5:

      [libc++] Merge is_scoped_enum.h into is_enum.h (#99458)

commit e361394633fe91f1b2bd3fb41f02942106f41041
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:13:12 2024 +0200

    libcxx-compat: revert llvmorg-19-init-18063-g561246e90282:

      [libc++][NFC] Remove wrong #endif comment

commit e6434521cff45652fff64c031d96556a618c1bc2
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:08:49 2024 +0200

    libcxx cstdlib, cwchar: avoid using long long functions if not
    supported, even for older compilers that do not support the
    using_if_exists attribute.

commit 45a1631c605889c06e9bb403819082f006ae7284
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:07:28 2024 +0200

    libcxx atomic_ref.h: add typename keyword for difference_type
    declarations, otherwise older clang versions cannot compile this header.

commit 9208b7928024bfaf402dc52c2352e90528f9133c
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Aug 5 22:05:46 2024 +0200

    libcxx simd_utils.h: only enable _LIBCPP_HAS_ALGORITHM_VECTOR_UTILS for
    clang >= 15, since older versions do not support the required builtins.

commit ce6d8506bfbf66858d05b72d158cdeeb2a9ea0b0
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Jul 31 22:16:45 2024 +0200

    Tentatively apply https://github.com/llvm/llvm-project/pull/101403.

commit ee4405ef3409d02caa69a6f483932d2e45d23029
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Jul 31 21:24:22 2024 +0200

    Remove OLD_DIRS+=usr/include/c++/v1/__pstl, since it has reappeared.

commit a6d4b3956a01335c611040f67ee4953d1068a0fb
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Jul 31 11:43:50 2024 +0200

    Fix enum warning in ath_hal's ar9002

    This fixes a clang 19 warning:

        sys/dev/ath/ath_hal/ar9002/ar9285_btcoex.c:57:32: error: comparison of different enumeration types ('HAL_BOOL' and 'HAL_ANT_SETTING') [-Werror,-Wenum-compare]
           57 |             (AH5212(ah)->ah_diversity != HAL_ANT_VARIABLE)) {
              |              ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~

    The `ah_diversity` field of `struct ath_hal_5212` is of type `HAL_BOOL`,
    not the enum type `HAL_ANT_SETTING`. In other code, `ah_diversity` is
    set to `AH_TRUE` whenever the related field `ah_antControl` is set to
    `HAL_ANT_VARIABLE`.

    It is not entirely clear to me what the intended statement is here: the
    test as it is written now compares the enum value 0 to `ah_diversity`,
    so in effect it enables the following block whenever `ah_diversity` is
    `AH_TRUE`. Write it like that, to avoid the compiler warning.

    MFC after:	3 days

commit 85e55b69f9aa473ff3e1c367cbd497970a1866c0
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Jul 31 11:03:17 2024 +0200

    Add one missed file for MK_COV to libllvm.

commit af9a17b143e0bd492b3aeb05f6a2207a3cca8d85
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Jul 31 00:21:35 2024 +0200

    Add more missed files to libclang for static analyzer.

commit 02ba73ed88c5a3396c2efe32648788be90907a7d
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Jul 30 20:28:51 2024 +0200

    Similar to gcc >= 8.1, turn off -Werror for -Wcast-function-type-mismatch.

commit b87ad27ddc1d0885ffc40d4186a4252b319dc751
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Jul 30 16:47:18 2024 +0200

    Bump llvm-project version numbers to llvmorg-19.1.0-rc1-0-ga4902a36d5c2 (and 19.1.0).

    PR:		280562
    MFC after:	1 month

commit 4f4a96b2c39a6a67be79b4f8cad94f4dcb872c73
Merge: adaf889b21c9 c76260f306a7
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Jul 30 16:27:43 2024 +0200

    Merge llvm-project release/19.x llvmorg-19.1.0-rc1-0-ga4902a36d5c2

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project release/19.x llvmorg-19.1.0-rc1-0-ga4902a36d5c2.

    PR:		280562
    MFC after:	1 month

commit adaf889b21c938d5c385b6ad60d661176d2b83a6
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Jul 30 15:17:44 2024 +0200

    Add one new builtin to compiler-rt.

    PR:		280562
    MFC after:	1 month

commit a87e7aa5a9bd6c1d63f0aced27084f7584a7c1af
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Jul 29 22:48:11 2024 +0200

    Update libomp generated headers

    PR:		280562
    MFC after:	1 month

commit a0dd67e4a35ca32dc63a2f4254c716b234c3bdd3
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Jul 29 22:42:24 2024 +0200

    Update build glue for libclang_rt

    PR:		280562
    MFC after:	1 month

commit 01772dc6a55632fb848951c8bffccd30247301b4
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Jul 29 22:41:55 2024 +0200

    Get rid of lib/libclang_rt/asan/warn.txt.

commit 1f65d58c9a70ccf10f513ceb9365fe787a134d3d
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Mon Jul 29 20:14:39 2024 +0200

    Update build glue for libc++

    PR:		280562
    MFC after:	1 month

commit 1769c4f43f1edc306ba7f29ad3361b7c7869e19b
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 23:00:00 2024 +0200

    Update build glue to build lldb

    PR:		280562
    MFC after:	1 month

commit b6a31b702b6238f7c01c2c24fb07c7ed888f64c7
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 21:58:23 2024 +0200

    Regenerate lib/clang/liblldb/LLDBWrapLua.cpp.

    PR:		280562
    MFC after:	1 month

commit fcb68a763d3099ff11663b5854f84af5ba2447e4
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 21:57:16 2024 +0200

    Update build glue to build llvm extra tools.

    PR:		280562
    MFC after:	1 month

commit b59e4576104ba2e8b07233bdd0fa1bc9f247237c
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 21:32:41 2024 +0200

    Update build glue to build full clang (with static analyzer).

    PR:		280562
    MFC after:	1 month

commit a5067c95b03f2cb9a2a67b7e99ea2372a3396f15
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 21:16:33 2024 +0200

    Update build glue to build default llvm tools for world.

    PR:		280562
    MFC after:	1 month

commit bd96f3373dbc4042ec69b80701faa569352c6cce
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 21:12:44 2024 +0200

    Update build glue to build minimal clang.

    PR:		280562
    MFC after:	1 month

commit 45dd9212d7f18381f2d7c94221e3e3a4edddce6f
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 20:21:54 2024 +0200

    Update tblgen-generated header lists.

    PR:		280562
    MFC after:	1 month

commit 36155ae45c0c400846c075e9eda600f6536972e0
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 17:26:39 2024 +0200

    Remove deleted sources from libllvm and libclang Makefiles.

    PR:		280562
    MFC after:	1 month

commit b5583751c0ac4ea41d396e0bd9808aeba041b8f7
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 16:19:52 2024 +0200

    Update libllvmminimal, llvm-tblgen and clang-tblgen Makefiles.

    PR:		280562
    MFC after:	1 month

commit 5531922846749943caa44fb617457b418840ca0e
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 15:24:46 2024 +0200

    Update FREEBSD-Xlist for llvm 19

    PR:		280562
    MFC after:	1 month

commit c2a811ef292182a1f2814f9d7dce6845c0ec73a5
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 15:23:09 2024 +0200

    Bump llvm-project numbers from 18.1.6 to 19.0.0

    PR:		280562
    MFC after:	1 month

commit 1891b2905585957146ae2c48752b84b700646749
Merge: 72f5e9833f16 ac9a064cb179
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Jul 28 01:34:35 2024 +0200

    Merge llvm-project main llvmorg-19-init-18630-gf2ccf80136a0

    This updates llvm, clang, compiler-rt, libc++, libunwind, lld, lldb and
    openmp to llvm-project main llvmorg-19-init-18630-gf2ccf80136a0, the
    last commit before the upstream release/19.x branch was created.

    PR:		280562
    MFC after:	1 month

commit 0370629593a68f2e04a9710d201d120a2ce437d4
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Oct 8 14:29:50 2024 +0200

    Vendor import of llvm-project branch release/19.x llvmorg-19.1.1-0-gd401987fe349, a.k.a. 19.1.1 release.

commit 1de139fdd502e836552eba1049a42b45514d8f7b
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Sep 22 11:37:02 2024 +0200

    Vendor import of llvm-project branch release/19.x llvmorg-19.1.0-0-ga4bf6cd7cfb1, a.k.a. 19.1.0 release.

commit 7432c96084d72c631f1e5ddf1cc2e24fd9c92482
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Wed Sep 4 16:11:41 2024 +0200

    Vendor import of llvm-project branch release/19.x llvmorg-19.1.0-rc4-0-g0c641568515a.

commit adf62863f35c84e4c5708f3dc5a1589ce958a238
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sun Aug 25 12:56:24 2024 +0200

    Vendor import of llvm-project branch release/19.x llvmorg-19.1.0-rc3-0-g437434df21d8.

commit 9b9503334fa856ed4ed6823d35b6f52546296f77
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Tue Aug 6 12:54:55 2024 +0200

    Vendor import of llvm-project branch release/19.x llvmorg-19.1.0-rc2-0-gd033ae172d1c.

commit c76260f306a7e51ef52dc75c6031e51e1e0862d7
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sat Jul 27 00:12:49 2024 +0200

    Vendor import of llvm-project branch release/19.x llvmorg-19.1.0-rc1-0-ga4902a36d5c2.

commit ac9a064cb179f3425b310fa2847f8764ac970a4d
Author: Dimitry Andric <dim@FreeBSD.org>
Date:   Sat Jul 27 00:04:10 2024 +0200

    Vendor import of llvm-project main llvmorg-19-init-18630-gf2ccf80136a0,
    the last commit before the upstream release/19.x branch was created.