build fix for unused var
/usr/home/user/src/freebsd-src/sys/dev/thunderbolt/router.c:1011:12: error: variable 'adap_num' set but not used [-Werror,-Wunused-but-set-variable]
 1011 |         uint8_t                 adap_num;
      |                                 ^