Revert "auditdistd: fix building with OpenSSL 3.0"
--- all_subdir_usr.sbin/auditdistd ---
/tmp/cirrus-ci-build/contrib/openbsm/bin/auditdistd/proto_tls.c:374:2: error: call to undeclared function 'SSL_load_error_strings'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
        SSL_load_error_strings();
        ^
/tmp/cirrus-ci-build/contrib/openbsm/bin/auditdistd/proto_tls.c:374:2: note: did you mean 'ERR_lib_error_string'?
/usr/obj/tmp/cirrus-ci-build/amd64.amd64/tmp/usr/include/openssl/err.h:239:13: note: 'ERR_lib_error_string' declared here
const char *ERR_lib_error_string(unsigned long e);
            ^
--- all_subdir_tests ---
--- page_fault_signal.debug ---
--- all_subdir_usr.sbin ---
/tmp/cirrus-ci-build/contrib/openbsm/bin/auditdistd/proto_tls.c:375:2: error: call to undeclared function 'SSL_library_init'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
--- all_subdir_tests ---
objcopy --only-keep-debug page_fault_signal.full page_fault_signal.debug
--- page_fault_signal ---
--- all_subdir_usr.sbin ---
        SSL_library_init();
        ^
/tmp/cirrus-ci-build/contrib/openbsm/bin/auditdistd/proto_tls.c:666:2: error: call to undeclared function 'SSL_load_error_strings'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
        SSL_load_error_strings();
        ^
/tmp/cirrus-ci-build/contrib/openbsm/bin/auditdistd/proto_tls.c:667:2: error: call to undeclared function 'SSL_library_init'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
        SSL_library_init();
        ^
--- all_subdir_tests ---
objcopy --strip-debug --add-gnu-debuglink=page_fault_signal.debug  page_fault_signal.full page_fault_signal
--- shared_shadow_inval_test ---
(cd /tmp/cirrus-ci-build/tests/sys/vm &&  DEPENDFILE=.depend.shared_shadow_inval_test  NO_SUBDIR=1 make -f /tmp/cirrus-ci-build/tests/sys/vm/Makefile _RECURSING_PROGS=t  PROG=shared_shadow_inval_test )
--- all_subdir_usr.sbin ---
4 errors generated.
--- all_subdir_lib ---
--- test_read_format_cpio_bin_Z.o ---
--- all_subdir_usr.sbin ---
*** [proto_tls.o] Error code 1
make[4]: stopped in /tmp/cirrus-ci-build/usr.sbin/auditdistd
--- all_subdir_lib ---

This reverts commit 7dd05498b290dfe360981ef7669c573fc05a55f3.