Cirrus-CI: Switch to 14.2 snap image
It seems that we end up using the host compiler for building
sys/modules/drm-kmod -- previously we used a 13.0 image (which has
Clang 11) and the build failed with

    error: unknown warning option '-Wno-unused-but-set-variable';
      did you mean '-Wno-unused-const-variable'?
      [-Werror,-Wunknown-warning-option]

in a drm-kmod subdirectory.