Revert "decryptcore: fix building with OpenSSL 3.0"
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:183:2: error: call to undeclared function 'ERR_load_crypto_strings'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
        ERR_load_crypto_strings();
        ^
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:194:7: error: call to undeclared function 'ERR_error_string'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
                    ERR_error_string(ERR_get_error(), NULL));
                    ^
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:194:24: error: call to undeclared function 'ERR_get_error'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
                    ERR_error_string(ERR_get_error(), NULL));
                                     ^
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:194:7: error: format specifies type 'char *' but the argument has type 'int' [-Werror,-Wformat]
                    ERR_error_string(ERR_get_error(), NULL));
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/cirrus-ci-build/lib/libpjdlog/pjdlog.h:106:44: note: expanded from macro 'pjdlog_error'
                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/tmp/cirrus-ci-build/lib/libpjdlog/pjdlog.h:97:35: note: expanded from macro 'pjdlog'
        pjdlog_common((loglevel), 0, -1, __VA_ARGS__)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/tmp/cirrus-ci-build/lib/libpjdlog/pjdlog.h:92:29: note: expanded from macro 'pjdlog_common'
            (debuglevel), (error), __VA_ARGS__)
                                   ^~~~~~~~~~~
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:240:7: error: call to undeclared function 'ERR_error_string'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
                    ERR_error_string(ERR_get_error(), NULL));
                    ^
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:240:24: error: call to undeclared function 'ERR_get_error'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
                    ERR_error_string(ERR_get_error(), NULL));
                                     ^
/tmp/cirrus-ci-build/sbin/decryptcore/decryptcore.c:240:7: error: format specifies type 'char *' but the argument has type 'int' [-Werror,-Wformat]
                    ERR_error_string(ERR_get_error(), NULL));
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/cirrus-ci-build/lib/libpjdlog/pjdlog.h:106:44: note: expanded from macro 'pjdlog_error'
                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/tmp/cirrus-ci-build/lib/libpjdlog/pjdlog.h:97:35: note: expanded from macro 'pjdlog'
        pjdlog_common((loglevel), 0, -1, __VA_ARGS__)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/tmp/cirrus-ci-build/lib/libpjdlog/pjdlog.h:92:29: note: expanded from macro 'pjdlog_common'
            (debuglevel), (error), __VA_ARGS__)
                                   ^~~~~~~~~~~
7 errors generated.
*** [decryptcore.o] Error code 1

This reverts commit a8c6ada6d9a721b9291a1499950ca872b5d00139.