libarchive: Avoid a build error with OpenSSL 3.0.8
This disables warning-errors for:

    archive_hmac.c:241:64: error: passing argument 2 of
    'OSSL_PARAM_construct_utf8_string' discards 'const' qualifier from
    pointer target type [-Werror=discarded-qualifiers]

(cherry picked from commit c9f9966904f144654cd2a032acfc4808d88ad53e)